export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const GET_SUBMISSIONS = 'GET_SUBMISSIONS';
export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_SUBMISSIONS = 'SET_SUBMISSIONS';
export const SUBMIT_CLIENT = 'SUBMIT_CLIENT';
export const SUBMIT_ACCOUNT = 'SUBMIT_ACCOUNT';
export const SUBMIT_CALC = 'SUBMIT_CALC';

export default { GET_CLIENTS, GET_ACCOUNTS, GET_SUBMISSIONS,
  SET_CLIENTS, SET_ACCOUNTS, SET_SUBMISSIONS,
  SUBMIT_CLIENT, SUBMIT_ACCOUNT, SUBMIT_CALC };
